const ADD_SERVICE = 'ADD_SERVICE';
const REMOVE_SERVICE = 'REMOVE_SERVICE';
const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
const EDIT_SERVICE = 'EDIT_SERVICE_FIELD';
const CLEAR_SERVICE = 'CLEAR_SERVICE';
const FILTER_SERVICE = 'FILTER_SERVICE';
const RENDER_FILTERED_SERVICES = 'RENDER_FILTERED_SERVICES';

export { ADD_SERVICE, REMOVE_SERVICE, CHANGE_SERVICE_FIELD, EDIT_SERVICE, CLEAR_SERVICE, FILTER_SERVICE, RENDER_FILTERED_SERVICES }
